### PR TITLE
Fix up docs

### LINKED ISSUE #2: Document refresh() method in README
A `refresh()` method exists that allows the wrapped component to tell wiretie that it would like the model to update, even though the props that generate the keys for wiretie haven't changed.  An example for this is if the wrapped component is getting a list as a wired-up model prop, and it knows that an entry to that list has been added/deleted.

### PR DESCRIPTION
**Pull request by developit**
Once merged, this fixes #2.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -68,6 +68,30 @@ export default function wire(contextNamespace, mapToProps={}, mapModelToProps=no
 
 			this.mapping = mapModelToProps(get(context, contextNamespace), props);
 
+			/** Props passed to your wrapped component.
+			 *	@name props
```
Comment (billneff79) [inline src/index.js:72]: Should we say something like "in addition to the props specified in `mapToProps` and `mapModelToProps`...

**Review by billneff79 — APPROVED** [review]

File: src/index.js (hunk 1 above)
Comment (developit) [reply src/index.js:72]: not sure.
